### ISSUE TITLE
Type styles

### ISSUE THREAD

**Issue by KirstenMaxco** [KirstenMaxco/THT-website#2]
Ul and OL are larger than p style - is this intentional?
![screen shot 2016-07-12 at 11 32 37 am](https://cloud.githubusercontent.com/assets/19725689/16752397/68d6aac6-4824-11e6-8b60-1ef09c3374c0.png)

Can links have a colour as well as the underline on hover? Worried they will be lost. Footer green. 
![screen shot 2016-07-12 at 11 32 54 am](https://cloud.githubusercontent.com/assets/19725689/16752412/8d9538f0-4824-11e6-85ad-d83895810060.png)

Style of h3 (in image dl bistro menu text)- can this pls be same styling as the menu sections heading (eg oysters on left) but when linked be footer green as above comment.

![screen shot 2016-07-12 at 11 36 45 am](https://cloud.githubusercontent.com/assets/19725689/16752501/26c4f010-4825-11e6-9941-a640b1bcf9b9.png)

**Comment by lawrymaxco** [comment]
Done

**Comment by KirstenMaxco** [comment]
green to stay on pls.

**Comment by lawrymaxco** [comment]
Hip Horray
