### ISSUE TITLE
Question - should padding be built in to image or text styles...

### ISSUE THREAD

**Issue by KirstenMaxco** [KirstenMaxco/THT-website#4]
Question - should padding be built in to image or text styles or should i manually break things like this?

![screen shot 2016-07-12 at 12 22 38 pm](https://cloud.githubusercontent.com/assets/19725689/16753230/7d8d8866-482b-11e6-9c2c-a1dc7361a789.png)

**Comment by lawrymaxco** [comment]
I didn't even fix this and its working
