### ISSUE TITLE
Jens comment about linking to feros site

### ISSUE THREAD

**Issue by KirstenMaxco** [KirstenMaxco/THT-website#5]
"    How do customers access / link to Feros group website and can we have links at the bottom for employment opportunities etc as a lot of people will just go to the relevant venue page (not knowing it’s part of Feros Group).  Should we also have ‘About Feros Group’ on there?"

Make the logo in the footer a link? I feel like that would suffice - if not then add a bit of "learn more about fros group here " in the footer.

**Comment by lawrymaxco** [comment]
Made all da links
