### ISSUE TITLE
Jen comment about websites tag line

### ISSUE THREAD

**Issue by KirstenMaxco** [KirstenMaxco/THT-website#8]
"The ‘about us’ line at the top needs to be made more prominent or removed – it gets too lost there.  I’d like to see it made more prominent if possible as I think it’s important to highlight our facilities quickly.  I’ll need to provide you with an update version of that line."

i like the tag line... but I see what she means. - discuss

**Comment by lawrymaxco** [comment]
Done - You can edit this sentence in the backend
